# Generated by Django 4.2.16 on 2024-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.TextField(),
        ),
    ]
